version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "cb:81:dc:09:4b:d9:87:89:f4:8d:7a:71:ab:96:0c:1c"
      - checkout
      - run:
          process.env.REACT_APP_PROD_API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
          process.env.REACT_APP_PROD_WEBSOCKET_URL = process.env.REACT_APP_WEBSOCKET_URL;
          name: Push Master to Production
          command: |
            git push https://github.com/marcelloak/scheduler.git master:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build